import Head from "next/head";
import Image from "next/image";
import GameCard from "../src/components/GameCard/GameCard.jsx";

import { API_KEY } from "../src/data/apiKey.js";
import httpRequest from "../src/lib/httpRequest";

const Home = (props) => {
  console.log(props);
  // console.table(props.topTenGames);

  const { topTen_CurrentGames } = props;

  console.log(topTen_CurrentGames);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {topTen_CurrentGames?.map((gameData) => (
          <GameCard
            key={gameData.id}
            image={gameData.background_image}
            name={gameData.name}
          />
        ))}
      </main>

      <footer>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const currentYear = new Date().getFullYear();

  // Most popular games in current year
  const apiData = await httpRequest(
    `https://api.rawg.io/api/games?key=${API_KEY}&dates=${currentYear}-01-01,${currentYear}-12-31&ordering=-added`
  );

  // const apiData = await httpRequest(
  //   `https://api.rawg.io/api/games?key=${API_KEY}`
  // );

  const topTen_CurrentGames = apiData.results.slice(0, 10);

  return {
    props: { topTen_CurrentGames },
  };
};
