import Head from "next/head";
import Image from "next/image";
import GameCard from "../components/GameCard/GameCard.jsx";

import httpRequest from "../lib/httpRequest";

const Home = (props) => {
  console.log(props);

  // const { topTenGames } = props.topTenGames;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {props.topTenGames.map((gameData) => (
          <GameCard
            key={gameData.id}
            image={gameData.background_image}
            name={gameData.name}
          />
        ))}
      </main>

      <footer>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const apiData = await httpRequest(
    "https://api.rawg.io/api/games?key=7624d1052a1c4ec68b3300e9bb3f12e7"
  );

  const topTenGames = apiData.results.slice(0, 10);

  return {
    props: { topTenGames },
  };
};
